version: '3.7'

services:
  app:
    build: .
    container_name: tbia-datahub-app-container
    image: tbia-datahub-app-image
    restart: always
    ports:
      - 8006:8006
    volumes:
      - .:/code
      - ../tbia-volumes/datahub_bucket:/bucket
      - ../tbia-volumes/bucket:/portal/bucket
      - ../tbia-volumes/solr:/solr
      - ../tbia-volumes/media:/portal/media
    depends_on:
      - postgres
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  postgres:
    build: ./postgres
    container_name: tbia-datahub-db-container
    image: tbia-datahub-db-image
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ../tbia-volumes/datahub_pgdata:/var/lib/postgresql/data/pgdata
      - ../tbia-volumes/datahub_bucket:/bucket
      - ../tbia-volumes/bucket:/portal/bucket
      - ../tbia-volumes/solr:/solr
      - ../tbia-volumes/media:/portal/media
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tbiadata
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    # command: -p 5433
  solr:
    build: ./solr-workspace
    image: solr:8.11.1
    container_name: tbia-solr
    ports:
      - "8983:8983"
    restart: always
    volumes:
      - ../tbia-volumes/solr:/var/solr
      - ./solr-workspace/:/workspace
    command:
      - solr-precreate
      - tbia_records
    environment:
      - SOLR_JAVA_MEM=-Xms4g -Xmx4g


