networks:
  datahub:
    external: true

services:
  app:
    build: .
    container_name: tbia-datahub-app-container
    image: tbia-datahub-app-image
    restart: always
    ports:
      - 8006:8006
    volumes:
      - .:/code
      - ../tbia-volumes/datahub_bucket:/bucket
      - ../tbia-volumes/bucket:/portal/bucket
      - ../tbia-volumes/solr:/solr
      - ../tbia-volumes/media:/portal/media
    depends_on:
      - postgres-datahub
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  postgres-datahub:
    build: ./postgres
    container_name: tbia-datahub-db-container
    image: tbia-datahub-db-image
    restart: always
    volumes:
      - ../tbia-volumes/datahub_pgdata:/var/lib/postgresql/data/pgdata
      - ../tbia-volumes/datahub_bucket:/bucket
      - ../tbia-volumes/bucket:/portal/bucket
      - ../tbia-volumes/solr:/solr
      - ../tbia-volumes/media:/portal/media
    environment:
      - POSTGRES_HOST=postgres-datahub
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    shm_size: 1g
    command: |
            postgres
              -c work_mem=256MB
              -c maintenance_work_mem=1GB
    networks:
      - datahub
  solr:
    build: ./solr-workspace
    image: tbia-solr-image
    container_name: tbia-solr
    ports:
      - "127.0.0.1:8983:8983"
    restart: always
    volumes:
      - ../tbia-volumes/solr:/var/solr
      - ../tbia-volumes/datahub_bucket:/bucket
      - ./solr-workspace/:/workspace
    environment:
      - SOLR_JAVA_MEM=-Xms4g -Xmx4g