"""add standard latitude

Revision ID: 00e687f73ca5
Revises: 80ea8a0dd040
Create Date: 2023-09-18 05:46:10.536173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e687f73ca5'
down_revision: Union[str, None] = '80ea8a0dd040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('standardLatitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'standardLatitude')
    # ### end Alembic commands ###
