"""Add is_finished to  UpdateVersion 

Revision ID: 0543fd1ce474
Revises: 7b922aa67c42
Create Date: 2024-01-11 08:22:44.973775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0543fd1ce474'
down_revision: Union[str, None] = '7b922aa67c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_version', sa.Column('is_finished', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_version', 'is_finished')
    # ### end Alembic commands ###
