"""add catalogNumber index

Revision ID: 0b17f0e25271
Revises: 858afeb6727c
Create Date: 2024-11-06 08:25:47.325740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b17f0e25271'
down_revision: Union[str, None] = '858afeb6727c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_records_catalogNumber'), 'records', ['catalogNumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_catalogNumber'), table_name='records')
    # ### end Alembic commands ###
