"""add match_higher_taxon

Revision ID: 116ddfd3358f
Revises: afb671754c4e
Create Date: 2023-11-20 01:42:32.338438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116ddfd3358f'
down_revision: Union[str, None] = 'afb671754c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('match_higher_taxon', sa.Boolean(), server_default='f', nullable=False))
    op.drop_index('ix_match_log_parentTaxonID', table_name='match_log')
    op.drop_column('match_log', 'parentTaxonID')
    op.add_column('records', sa.Column('match_higher_taxon', sa.Boolean(), server_default='f', nullable=False))
    op.drop_index('ix_records_parentTaxonID', table_name='records')
    op.drop_column('records', 'parentTaxonID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('parentTaxonID', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_records_parentTaxonID', 'records', ['parentTaxonID'], unique=False)
    op.drop_column('records', 'match_higher_taxon')
    op.add_column('match_log', sa.Column('parentTaxonID', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_match_log_parentTaxonID', 'match_log', ['parentTaxonID'], unique=False)
    op.drop_column('match_log', 'match_higher_taxon')
    # ### end Alembic commands ###
