"""update match_log

Revision ID: 2df55550db06
Revises: a5e4e91d9fd2
Create Date: 2024-03-22 11:22:46.067617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df55550db06'
down_revision: Union[str, None] = 'a5e4e91d9fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbiaid_unique', 'match_log', type_='unique')
    op.create_unique_constraint('matchlog_unique', 'match_log', ['tbiaID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matchlog_unique', 'match_log', type_='unique')
    op.create_unique_constraint('tbiaid_unique', 'match_log', ['tbiaID'])
    # ### end Alembic commands ###
