"""remove deleted records

Revision ID: 2e19915a8a03
Revises: acee386c0c00
Create Date: 2026-04-30 07:05:13.015346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e19915a8a03'
down_revision: Union[str, None] = 'acee386c0c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_records_catalogNumber', table_name='deleted_records')
    op.drop_index('ix_deleted_records_group', table_name='deleted_records')
    op.drop_index('ix_deleted_records_occurrenceID', table_name='deleted_records')
    op.drop_index('ix_deleted_records_rights_holder', table_name='deleted_records')
    op.drop_index('ix_deleted_records_tbiaID', table_name='deleted_records')
    op.drop_table('deleted_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tbiaID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('group', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rights_holder', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('occurrenceID', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('catalogNumber', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='deleted_records_pkey')
    )
    op.create_index('ix_deleted_records_tbiaID', 'deleted_records', ['tbiaID'], unique=False)
    op.create_index('ix_deleted_records_rights_holder', 'deleted_records', ['rights_holder'], unique=False)
    op.create_index('ix_deleted_records_occurrenceID', 'deleted_records', ['occurrenceID'], unique=False)
    op.create_index('ix_deleted_records_group', 'deleted_records', ['group'], unique=False)
    op.create_index('ix_deleted_records_catalogNumber', 'deleted_records', ['catalogNumber'], unique=False)
    # ### end Alembic commands ###
