"""add municipality

Revision ID: 359c02095417
Revises: 6aa164420256
Create Date: 2025-01-03 07:10:16.622755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359c02095417'
down_revision: Union[str, None] = '6aa164420256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('municipality', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('raw_municipality', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'raw_municipality')
    op.drop_column('records', 'municipality')
    # ### end Alembic commands ###
