"""add taxon table

Revision ID: 4ba7c937a550
Revises: dc460ff16e65
Create Date: 2023-09-14 02:27:47.587300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba7c937a550'
down_revision: Union[str, None] = 'dc460ff16e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxonID', sa.String(length=10), nullable=False),
    sa.Column('name_status', sa.String(length=20), nullable=False),
    sa.Column('aberration', sa.String(length=10000), nullable=True),
    sa.Column('aberration_c', sa.String(length=10000), nullable=True),
    sa.Column('alternative_name_c', sa.String(length=10000), nullable=True),
    sa.Column('class', sa.String(length=10000), nullable=True),
    sa.Column('class_c', sa.String(length=10000), nullable=True),
    sa.Column('common_name_c', sa.String(length=10000), nullable=True),
    sa.Column('division', sa.String(length=10000), nullable=True),
    sa.Column('division_c', sa.String(length=10000), nullable=True),
    sa.Column('domain', sa.String(length=10000), nullable=True),
    sa.Column('domain_c', sa.String(length=10000), nullable=True),
    sa.Column('family', sa.String(length=10000), nullable=True),
    sa.Column('family_c', sa.String(length=10000), nullable=True),
    sa.Column('formatted_genus', sa.String(length=10000), nullable=True),
    sa.Column('formatted_subgenus', sa.String(length=10000), nullable=True),
    sa.Column('formatted_section', sa.String(length=10000), nullable=True),
    sa.Column('formatted_subsection', sa.String(length=10000), nullable=True),
    sa.Column('formatted_species', sa.String(length=10000), nullable=True),
    sa.Column('formatted_subspecies', sa.String(length=10000), nullable=True),
    sa.Column('formatted_nothosubspecies', sa.String(length=10000), nullable=True),
    sa.Column('formatted_variety', sa.String(length=10000), nullable=True),
    sa.Column('formatted_subvariety', sa.String(length=10000), nullable=True),
    sa.Column('formatted_nothovariety', sa.String(length=10000), nullable=True),
    sa.Column('formatted_form', sa.String(length=10000), nullable=True),
    sa.Column('formatted_subform', sa.String(length=10000), nullable=True),
    sa.Column('formatted_specialform', sa.String(length=10000), nullable=True),
    sa.Column('formatted_race', sa.String(length=10000), nullable=True),
    sa.Column('formatted_strip', sa.String(length=10000), nullable=True),
    sa.Column('formatted_morph', sa.String(length=10000), nullable=True),
    sa.Column('formatted_aberration', sa.String(length=10000), nullable=True),
    sa.Column('formatted_hybridformula', sa.String(length=10000), nullable=True),
    sa.Column('formatted_name', sa.String(length=10000), nullable=True),
    sa.Column('formatted_synonyms', sa.String(length=10000), nullable=True),
    sa.Column('formatted_misapplied', sa.String(length=10000), nullable=True),
    sa.Column('form', sa.String(length=10000), nullable=True),
    sa.Column('form_c', sa.String(length=10000), nullable=True),
    sa.Column('genus', sa.String(length=10000), nullable=True),
    sa.Column('genus_c', sa.String(length=10000), nullable=True),
    sa.Column('hybridformula', sa.String(length=10000), nullable=True),
    sa.Column('hybridformula_c', sa.String(length=10000), nullable=True),
    sa.Column('infraclass', sa.String(length=10000), nullable=True),
    sa.Column('infraclass_c', sa.String(length=10000), nullable=True),
    sa.Column('infradivision', sa.String(length=10000), nullable=True),
    sa.Column('infradivision_c', sa.String(length=10000), nullable=True),
    sa.Column('infrakingdom', sa.String(length=10000), nullable=True),
    sa.Column('infrakingdom_c', sa.String(length=10000), nullable=True),
    sa.Column('infraorder', sa.String(length=10000), nullable=True),
    sa.Column('infraorder_c', sa.String(length=10000), nullable=True),
    sa.Column('infraphylum', sa.String(length=10000), nullable=True),
    sa.Column('infraphylum_c', sa.String(length=10000), nullable=True),
    sa.Column('kingdom', sa.String(length=10000), nullable=True),
    sa.Column('kingdom_c', sa.String(length=10000), nullable=True),
    sa.Column('microphylum', sa.String(length=10000), nullable=True),
    sa.Column('microphylum_c', sa.String(length=10000), nullable=True),
    sa.Column('misapplied', sa.String(length=10000), nullable=True),
    sa.Column('morph', sa.String(length=10000), nullable=True),
    sa.Column('morph_c', sa.String(length=10000), nullable=True),
    sa.Column('name_author', sa.String(length=10000), nullable=True),
    sa.Column('nothosubspecies', sa.String(length=10000), nullable=True),
    sa.Column('nothosubspecies_c', sa.String(length=10000), nullable=True),
    sa.Column('nothovariety', sa.String(length=10000), nullable=True),
    sa.Column('nothovariety_c', sa.String(length=10000), nullable=True),
    sa.Column('order', sa.String(length=10000), nullable=True),
    sa.Column('order_c', sa.String(length=10000), nullable=True),
    sa.Column('parvdivision', sa.String(length=10000), nullable=True),
    sa.Column('parvdivision_c', sa.String(length=10000), nullable=True),
    sa.Column('parvphylum', sa.String(length=10000), nullable=True),
    sa.Column('parvphylum_c', sa.String(length=10000), nullable=True),
    sa.Column('phylum', sa.String(length=10000), nullable=True),
    sa.Column('phylum_c', sa.String(length=10000), nullable=True),
    sa.Column('race', sa.String(length=10000), nullable=True),
    sa.Column('race_c', sa.String(length=10000), nullable=True),
    sa.Column('scientificName', sa.String(length=10000), nullable=True),
    sa.Column('scientificNameID', sa.String(length=10000), nullable=True),
    sa.Column('section', sa.String(length=10000), nullable=True),
    sa.Column('section_c', sa.String(length=10000), nullable=True),
    sa.Column('specialform', sa.String(length=10000), nullable=True),
    sa.Column('specialform_c', sa.String(length=10000), nullable=True),
    sa.Column('species', sa.String(length=10000), nullable=True),
    sa.Column('species_c', sa.String(length=10000), nullable=True),
    sa.Column('stirp', sa.String(length=10000), nullable=True),
    sa.Column('stirp_c', sa.String(length=10000), nullable=True),
    sa.Column('subclass', sa.String(length=10000), nullable=True),
    sa.Column('subclass_c', sa.String(length=10000), nullable=True),
    sa.Column('subdivision', sa.String(length=10000), nullable=True),
    sa.Column('subdivision_c', sa.String(length=10000), nullable=True),
    sa.Column('subfamily', sa.String(length=10000), nullable=True),
    sa.Column('subfamily_c', sa.String(length=10000), nullable=True),
    sa.Column('subform', sa.String(length=10000), nullable=True),
    sa.Column('subform_c', sa.String(length=10000), nullable=True),
    sa.Column('subgenus', sa.String(length=10000), nullable=True),
    sa.Column('subgenus_c', sa.String(length=10000), nullable=True),
    sa.Column('subkingdom', sa.String(length=10000), nullable=True),
    sa.Column('subkingdom_c', sa.String(length=10000), nullable=True),
    sa.Column('suborder', sa.String(length=10000), nullable=True),
    sa.Column('suborder_c', sa.String(length=10000), nullable=True),
    sa.Column('subphylum', sa.String(length=10000), nullable=True),
    sa.Column('subphylum_c', sa.String(length=10000), nullable=True),
    sa.Column('subsection', sa.String(length=10000), nullable=True),
    sa.Column('subsection_c', sa.String(length=10000), nullable=True),
    sa.Column('subspecies', sa.String(length=10000), nullable=True),
    sa.Column('subspecies_c', sa.String(length=10000), nullable=True),
    sa.Column('subtribe', sa.String(length=10000), nullable=True),
    sa.Column('subtribe_c', sa.String(length=10000), nullable=True),
    sa.Column('subvariety', sa.String(length=10000), nullable=True),
    sa.Column('subvariety_c', sa.String(length=10000), nullable=True),
    sa.Column('superclass', sa.String(length=10000), nullable=True),
    sa.Column('superclass_c', sa.String(length=10000), nullable=True),
    sa.Column('superdivision', sa.String(length=10000), nullable=True),
    sa.Column('superdivision_c', sa.String(length=10000), nullable=True),
    sa.Column('superfamily', sa.String(length=10000), nullable=True),
    sa.Column('superfamily_c', sa.String(length=10000), nullable=True),
    sa.Column('superkingdom', sa.String(length=10000), nullable=True),
    sa.Column('superkingdom_c', sa.String(length=10000), nullable=True),
    sa.Column('superorder', sa.String(length=10000), nullable=True),
    sa.Column('superorder_c', sa.String(length=10000), nullable=True),
    sa.Column('superphylum', sa.String(length=10000), nullable=True),
    sa.Column('superphylum_c', sa.String(length=10000), nullable=True),
    sa.Column('synonyms', sa.String(length=10000), nullable=True),
    sa.Column('taxonRank', sa.String(length=10000), nullable=True),
    sa.Column('tribe', sa.String(length=10000), nullable=True),
    sa.Column('tribe_c', sa.String(length=10000), nullable=True),
    sa.Column('variety', sa.String(length=10000), nullable=True),
    sa.Column('variety_c', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxon_name_status'), 'taxon', ['name_status'], unique=False)
    op.create_index(op.f('ix_taxon_taxonID'), 'taxon', ['taxonID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxon_taxonID'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_name_status'), table_name='taxon')
    op.drop_table('taxon')
    # ### end Alembic commands ###
