"""add match_higher_partial

Revision ID: 4bd719e1ecb9
Revises: 5bbfece62b6c
Create Date: 2026-07-02 08:56:10.811399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd719e1ecb9'
down_revision: Union[str, None] = '5bbfece62b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('match_higher_partial', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_log', 'match_higher_partial')
    # ### end Alembic commands ###
