"""add sourceOrder

Revision ID: 4dfcb92fa899
Revises: 5327ea1908ac
Create Date: 2023-10-18 08:26:17.150726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfcb92fa899'
down_revision: Union[str, None] = '5327ea1908ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sourceOrder', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'sourceOrder')
    # ### end Alembic commands ###
