"""add index to is_deleted

Revision ID: 4fe2d13eb227
Revises: fff967284e7a
Create Date: 2023-10-13 03:41:27.046950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe2d13eb227'
down_revision: Union[str, None] = 'fff967284e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_records_is_deleted'), 'records', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_is_deleted'), table_name='records')
    # ### end Alembic commands ###
