"""add sourceFamily & sourceClass

Revision ID: 5327ea1908ac
Revises: a1dedfcb2553
Create Date: 2023-10-18 08:10:11.445511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5327ea1908ac'
down_revision: Union[str, None] = 'a1dedfcb2553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sourceFamily', sa.String(length=1000), nullable=True))
    op.add_column('records', sa.Column('sourceClass', sa.String(length=1000), nullable=True))
    op.drop_index('ix_records_sourceTaxonRank', table_name='records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_records_sourceTaxonRank', 'records', ['sourceTaxonRank'], unique=False)
    op.drop_column('records', 'sourceClass')
    op.drop_column('records', 'sourceFamily')
    # ### end Alembic commands ###
