"""alter taxon table

Revision ID: 5b8612e3d1d3
Revises: b4bbc9442b7c
Create Date: 2026-04-23 02:37:58.769656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8612e3d1d3'
down_revision: Union[str, None] = 'b4bbc9442b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxon', 'formatted_genus',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subgenus',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_section',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subsection',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_species',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subspecies',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_nothosubspecies',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_variety',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subvariety',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_nothovariety',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_form',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subform',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_race',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_morph',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_aberration',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_name',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_synonyms',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_misapplied',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'misapplied',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'synonyms',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_kingdom',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subkingdom',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infrakingdom',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superphylum',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_phylum',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subphylum',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraphylum',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superclass',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_class',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subclass',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraclass',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superorder',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_order',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_family',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subfamily',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superfamily',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_suborder',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraorder',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_tribe',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subtribe',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_realm',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_unranked',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxon', 'formatted_unranked',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_realm',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subtribe',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_tribe',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraorder',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_suborder',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superfamily',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subfamily',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_family',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_order',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superorder',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraclass',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subclass',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_class',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superclass',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infraphylum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subphylum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_phylum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_superphylum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_infrakingdom',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subkingdom',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_kingdom',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'synonyms',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'misapplied',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_misapplied',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_synonyms',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_aberration',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_morph',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_race',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subform',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_form',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_nothovariety',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subvariety',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_variety',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_nothosubspecies',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subspecies',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_species',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subsection',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_section',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_subgenus',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.alter_column('taxon', 'formatted_genus',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
