"""Add total count to update_version

Revision ID: 5bbfece62b6c
Revises: 2e19915a8a03
Create Date: 2026-05-15 08:05:38.325844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbfece62b6c'
down_revision: Union[str, None] = '2e19915a8a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_version', sa.Column('total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_version', 'total_count')
    # ### end Alembic commands ###
