"""associatedMedia from string to text

Revision ID: 5e258ee6b18a
Revises: 4bd719e1ecb9
Create Date: 2026-07-31 05:47:00.607691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e258ee6b18a'
down_revision: Union[str, None] = '4bd719e1ecb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'associatedMedia',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'associatedMedia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
