"""add sourceTaxonID column

Revision ID: 60fbb385ee31
Revises: aad21c246d5a
Create Date: 2023-09-04 13:10:28.576509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fbb385ee31'
down_revision: Union[str, None] = 'aad21c246d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sourceTaxonID', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_records_sourceTaxonID'), 'records', ['sourceTaxonID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_sourceTaxonID'), table_name='records')
    op.drop_column('records', 'sourceTaxonID')
    # ### end Alembic commands ###
