"""add county, town

Revision ID: 6720016de3dc
Revises: 51c4fd61a5f8
Create Date: 2024-12-30 09:29:58.072961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6720016de3dc'
down_revision: Union[str, None] = '51c4fd61a5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.add_column('records', sa.Column('county', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('town', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'town')
    op.drop_column('records', 'county')
    op.alter_column('dataset', 'group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
