"""remove standard year, month, day

Revision ID: 6accebbc5c4a
Revises: 8fad79a9ad11
Create Date: 2025-01-08 07:45:14.524647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6accebbc5c4a'
down_revision: Union[str, None] = '8fad79a9ad11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'standardDay')
    op.drop_column('records', 'standardMonth')
    op.drop_column('records', 'standardYear')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('standardYear', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('standardMonth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('standardDay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
