"""Add UpdateVersion

Revision ID: 7b922aa67c42
Revises: e8975dcd7754
Create Date: 2024-01-11 07:56:07.741592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b922aa67c42'
down_revision: Union[str, None] = 'e8975dcd7754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_version', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('rights_holder', sa.String(length=10000), nullable=True),
    sa.Column('note', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rights_holder', 'update_version', name='update_unique')
    )
    op.create_index(op.f('ix_update_version_rights_holder'), 'update_version', ['rights_holder'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_version_rights_holder'), table_name='update_version')
    op.drop_table('update_version')
    # ### end Alembic commands ###
