"""alter collectionID to catalogNumber

Revision ID: 7da0c2681609
Revises: c722d1629043
Create Date: 2023-10-17 09:17:20.656661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da0c2681609'
down_revision: Union[str, None] = 'c722d1629043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('catalogNumber', sa.String(length=10000), nullable=True))
    op.drop_column('records', 'collectionID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('collectionID', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.drop_column('records', 'catalogNumber')
    # ### end Alembic commands ###
