"""remove name_status from taxon

Revision ID: 80ea8a0dd040
Revises: 4ba7c937a550
Create Date: 2023-09-14 02:43:17.649694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ea8a0dd040'
down_revision: Union[str, None] = '4ba7c937a550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_taxon_name_status', table_name='taxon')
    op.drop_column('taxon', 'name_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('name_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_taxon_name_status', 'taxon', ['name_status'], unique=False)
    # ### end Alembic commands ###
