"""add data quality

Revision ID: 858afeb6727c
Revises: 6b81d334069a
Create Date: 2024-10-24 03:33:15.798784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858afeb6727c'
down_revision: Union[str, None] = '6b81d334069a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('dataQuality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'dataQuality')
    # ### end Alembic commands ###
