"""remove unused matchlog index

Revision ID: 8d64c56bccf4
Revises: 97deeef6a0ef
Create Date: 2025-02-26 06:24:16.300028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d64c56bccf4'
down_revision: Union[str, None] = '97deeef6a0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_log_stage_1', table_name='match_log')
    op.drop_index('ix_match_log_stage_2', table_name='match_log')
    op.drop_index('ix_match_log_stage_3', table_name='match_log')
    op.drop_index('ix_match_log_stage_4', table_name='match_log')
    op.drop_index('ix_match_log_stage_5', table_name='match_log')
    op.drop_index('ix_match_log_stage_6', table_name='match_log')
    op.drop_index('ix_match_log_stage_7', table_name='match_log')
    op.drop_index('ix_match_log_stage_8', table_name='match_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_match_log_stage_8', 'match_log', ['stage_8'], unique=False)
    op.create_index('ix_match_log_stage_7', 'match_log', ['stage_7'], unique=False)
    op.create_index('ix_match_log_stage_6', 'match_log', ['stage_6'], unique=False)
    op.create_index('ix_match_log_stage_5', 'match_log', ['stage_5'], unique=False)
    op.create_index('ix_match_log_stage_4', 'match_log', ['stage_4'], unique=False)
    op.create_index('ix_match_log_stage_3', 'match_log', ['stage_3'], unique=False)
    op.create_index('ix_match_log_stage_2', 'match_log', ['stage_2'], unique=False)
    op.create_index('ix_match_log_stage_1', 'match_log', ['stage_1'], unique=False)
    # ### end Alembic commands ###
