"""update raw county cols

Revision ID: 8fad79a9ad11
Revises: 359c02095417
Create Date: 2025-01-06 06:39:16.890601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fad79a9ad11'
down_revision: Union[str, None] = '359c02095417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('rawCounty', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('rawMunicipality', sa.String(length=50), nullable=True))
    op.drop_column('records', 'raw_municipality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('raw_municipality', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('records', 'rawMunicipality')
    op.drop_column('records', 'rawCounty')
    # ### end Alembic commands ###
