"""remove unused index

Revision ID: 97deeef6a0ef
Revises: 3036f0271c5e
Create Date: 2025-02-26 05:52:05.665841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97deeef6a0ef'
down_revision: Union[str, None] = '3036f0271c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_created', table_name='records')
    op.drop_index('ix_records_datasetName', table_name='records')
    op.drop_index('ix_records_sourceScientificName', table_name='records')
    op.drop_index('ix_records_sourceVernacularName', table_name='records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_records_sourceVernacularName', 'records', ['sourceVernacularName'], unique=False)
    op.create_index('ix_records_sourceScientificName', 'records', ['sourceScientificName'], unique=False)
    op.create_index('ix_records_datasetName', 'records', ['datasetName'], unique=False)
    op.create_index('ix_records_created', 'records', ['created'], unique=False)
    # ### end Alembic commands ###
