"""add alien_type to taxon

Revision ID: a1dedfcb2553
Revises: a4c8fbdef21f
Create Date: 2023-10-18 05:23:02.147544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dedfcb2553'
down_revision: Union[str, None] = 'a4c8fbdef21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('alien_type', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon', 'alien_type')
    # ### end Alembic commands ###
