"""add associatedMediaType

Revision ID: acee386c0c00
Revises: 5b8612e3d1d3
Create Date: 2026-04-29 05:53:47.858548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acee386c0c00'
down_revision: Union[str, None] = '5b8612e3d1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('associatedMediaType', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'associatedMediaType')
    # ### end Alembic commands ###
