"""add deleted_records 

Revision ID: b067a0e0b6bd
Revises: f95313caf86e
Create Date: 2023-10-20 09:16:27.200823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b067a0e0b6bd'
down_revision: Union[str, None] = 'f95313caf86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tbiaID', sa.String(length=50), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('rights_holder', sa.String(length=10000), nullable=True),
    sa.Column('occurrenceID', sa.String(length=1000), nullable=True),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_records_group'), 'deleted_records', ['group'], unique=False)
    op.create_index(op.f('ix_deleted_records_occurrenceID'), 'deleted_records', ['occurrenceID'], unique=False)
    op.create_index(op.f('ix_deleted_records_rights_holder'), 'deleted_records', ['rights_holder'], unique=False)
    op.create_index(op.f('ix_deleted_records_tbiaID'), 'deleted_records', ['tbiaID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_records_tbiaID'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_rights_holder'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_occurrenceID'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_group'), table_name='deleted_records')
    op.drop_table('deleted_records')
    # ### end Alembic commands ###
