"""update stage type

Revision ID: b93ddfe0ef59
Revises: 60fbb385ee31
Create Date: 2023-09-11 09:05:47.304808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93ddfe0ef59'
down_revision: Union[str, None] = '60fbb385ee31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_log', 'stage_1',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_2',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_3',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_4',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_5',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_match_log_stage_1'), 'match_log', ['stage_1'], unique=False)
    op.create_index(op.f('ix_match_log_stage_2'), 'match_log', ['stage_2'], unique=False)
    op.create_index(op.f('ix_match_log_stage_3'), 'match_log', ['stage_3'], unique=False)
    op.create_index(op.f('ix_match_log_stage_4'), 'match_log', ['stage_4'], unique=False)
    op.create_index(op.f('ix_match_log_stage_5'), 'match_log', ['stage_5'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_log_stage_5'), table_name='match_log')
    op.drop_index(op.f('ix_match_log_stage_4'), table_name='match_log')
    op.drop_index(op.f('ix_match_log_stage_3'), table_name='match_log')
    op.drop_index(op.f('ix_match_log_stage_2'), table_name='match_log')
    op.drop_index(op.f('ix_match_log_stage_1'), table_name='match_log')
    op.alter_column('match_log', 'stage_5',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_4',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_3',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_2',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('match_log', 'stage_1',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
