"""add update version

Revision ID: bbf35a371076
Revises: 116ddfd3358f
Create Date: 2023-11-21 02:32:01.220933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf35a371076'
down_revision: Union[str, None] = '116ddfd3358f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('update_version', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_records_update_version'), 'records', ['update_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_update_version'), table_name='records')
    op.drop_column('records', 'update_version')
    # ### end Alembic commands ###
