"""add sourceKingdom

Revision ID: c10c735e9078
Revises: 8d64c56bccf4
Create Date: 2026-04-22 06:40:52.634006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10c735e9078'
down_revision: Union[str, None] = '8d64c56bccf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sourceKingdom', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'sourceKingdom')
    # ### end Alembic commands ###
