"""originalScientificName to originalVernacularName

Revision ID: d4c6b4d0751e
Revises: 774778e90af8
Create Date: 2024-03-22 02:18:54.813209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c6b4d0751e'
down_revision: Union[str, None] = '774778e90af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rights_holder', sa.String(length=10000), nullable=True),
    sa.Column('image_rule', sa.String(length=10000), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rights_holder', 'image_rule', name='rule_unique')
    )
    op.create_index(op.f('ix_image_rule_image_rule'), 'image_rule', ['image_rule'], unique=False)
    op.create_index(op.f('ix_image_rule_rights_holder'), 'image_rule', ['rights_holder'], unique=False)
    op.add_column('records', sa.Column('originalVernacularName', sa.String(length=10000), nullable=True))
    op.drop_index('ix_records_originalScientificName', table_name='records')
    op.create_index(op.f('ix_records_originalVernacularName'), 'records', ['originalVernacularName'], unique=False)
    op.drop_column('records', 'originalScientificName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('originalScientificName', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_records_originalVernacularName'), table_name='records')
    op.create_index('ix_records_originalScientificName', 'records', ['originalScientificName'], unique=False)
    op.drop_column('records', 'originalVernacularName')
    op.drop_index(op.f('ix_image_rule_rights_holder'), table_name='image_rule')
    op.drop_index(op.f('ix_image_rule_image_rule'), table_name='image_rule')
    op.drop_table('image_rule')
    # ### end Alembic commands ###
