"""add sourceDatasetID to records

Revision ID: ddc6d647bf01
Revises: 2df55550db06
Create Date: 2024-03-28 08:14:08.148287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc6d647bf01'
down_revision: Union[str, None] = '2df55550db06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sourceDatasetID', sa.String(length=10000), server_default='', nullable=True))
    op.create_index(op.f('ix_records_sourceDatasetID'), 'records', ['sourceDatasetID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_sourceDatasetID'), table_name='records')
    op.drop_column('records', 'sourceDatasetID')
    # ### end Alembic commands ###
