"""remove town

Revision ID: f06a8937941f
Revises: 6accebbc5c4a
Create Date: 2025-01-08 07:48:45.621159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06a8937941f'
down_revision: Union[str, None] = '6accebbc5c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'raw_town')
    op.drop_column('records', 'raw_county')
    op.drop_column('records', 'town')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('town', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('raw_county', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('raw_town', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
