"""update species_images

Revision ID: faaeb962ee36
Revises: 77da7ef589e1
Create Date: 2024-06-19 05:52:36.594735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faaeb962ee36'
down_revision: Union[str, None] = '77da7ef589e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species_images', sa.Column('taieol_url', sa.String(length=10000), nullable=True))
    op.add_column('species_images', sa.Column('taxon_id', sa.String(length=20), nullable=True))
    op.drop_constraint('namecode', 'species_images', type_='unique')
    op.create_unique_constraint('taxon_images', 'species_images', ['taxon_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taxon_images', 'species_images', type_='unique')
    op.create_unique_constraint('namecode', 'species_images', ['namecode', 'taxon_name_id'])
    op.drop_column('species_images', 'taxon_id')
    op.drop_column('species_images', 'taieol_url')
    # ### end Alembic commands ###
