"""add columns to records

Revision ID: fff967284e7a
Revises: 00e687f73ca5
Create Date: 2023-10-13 03:12:10.914953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff967284e7a'
down_revision: Union[str, None] = '00e687f73ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tbiaID_unique', 'match_log', ['tbiaID'])
    op.add_column('records', sa.Column('sourceOccurrenceID', sa.String(length=1000), nullable=True))
    op.add_column('records', sa.Column('sourceTaxonRank', sa.String(length=1000), nullable=True))
    op.add_column('records', sa.Column('standardYear', sa.Float(), nullable=True))
    op.add_column('records', sa.Column('standardMonth', sa.Float(), nullable=True))
    op.add_column('records', sa.Column('standardDay', sa.Float(), nullable=True))
    op.add_column('records', sa.Column('year', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('month', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('day', sa.String(length=50), nullable=True))
    op.add_column('records', sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False))
    op.create_index(op.f('ix_records_sourceOccurrenceID'), 'records', ['sourceOccurrenceID'], unique=False)
    op.create_index(op.f('ix_records_sourceTaxonRank'), 'records', ['sourceTaxonRank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_sourceTaxonRank'), table_name='records')
    op.drop_index(op.f('ix_records_sourceOccurrenceID'), table_name='records')
    op.drop_column('records', 'is_deleted')
    op.drop_column('records', 'day')
    op.drop_column('records', 'month')
    op.drop_column('records', 'year')
    op.drop_column('records', 'standardDay')
    op.drop_column('records', 'standardMonth')
    op.drop_column('records', 'standardYear')
    op.drop_column('records', 'sourceTaxonRank')
    op.drop_column('records', 'sourceOccurrenceID')
    op.drop_constraint('tbiaID_unique', 'match_log', type_='unique')
    # ### end Alembic commands ###
